django/omdapp/omdapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('admin/', admin.site.urls),
    path('', include('omdmain.urls'))
]

django/omdapp/omdmain/urls.py
from django.conf.urls import url, include
from . import views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import path

app_name = 'omdmain'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('home/', views.home.as_view(), name='home'),
    path('movies/', views.movies.as_view(), name='movies'),
    path('save_movie/', views.save_movie.as_view(), name='save_movie'),
    path('saved_movies/', views.saved_movies.as_view(), name='saved_movies'),
    path('', views.index.as_view())
]

django/omdapp/omdmain/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

class Movies(models.Model):
    movie_id = models.CharField(max_length=9, null=False, blank=False, verbose_name=_('movieId'))
    title = models.CharField(max_length=50, null=True, blank=True, verbose_name=_('title'))
    release = models.CharField(max_length=10, null=True, blank=True, verbose_name=_('release'))
    runtime = models.CharField(max_length=10, null=True, blank=True, verbose_name=_('runtime'))
    actors = models.CharField(max_length=50, null=True, blank=True, verbose_name=_('actors'))
    boxoffice = models.CharField(max_length=10, null=True, blank=True, verbose_name=_('boxoffice'))
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE,
                             verbose_name=_('user'))

django/omdapp/omdmain/forms.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ModelForm
from django.contrib.admin import widgets
from django.utils import timezone


class UserRegistrationForm(forms.Form):
	def __init__(self, *args, **kwargs):
		super(UserRegistrationForm, self).__init__(*args, **kwargs)

		for fieldname in ['username', 'email', 'password1', 'password2']:
			self.fields[fieldname].label = None

	username = forms.CharField(
		required=True,
		label='Username',
		max_length=30,
	)
	email = forms.CharField(
		required=True,
		label='Email',
		max_length=100,
	)
	password1 = forms.CharField(
		required=True,
		label='Password',
		max_length=100,
	)
	password2 = forms.CharField(
		required=True,
		label='Repeat password',
		max_length=100,
	)

	def clean_password2(self):
		if 'password1' in self.cleaned_data:
			password1 = self.cleaned_data['password1']
			password2 = self.cleaned_data['password2']
			if password1 == password2:
				return password2
		raise forms.ValidationError('Passwords do not match.')

django/omdapp/omdmain/views.py
import json
import requests
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login

from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist

from omdmain.forms import UserRegistrationForm
from omdmain.models import Movies

from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView



class index(TemplateView):
    template_name = 'index.html'

class home(TemplateView):
    template_name = 'home.html'

class movies(TemplateView):
    template_name = 'movies.html'

class save_movie(View):
    def post(self, request, *args, **kwargs):
        user = request.user

        data = json.loads(request.body)
        movie_id = data['imdbId']
        title = data['titleMovie']
        release = data['releaseMovie']
        runtime = data['runtimeMovie']
        actors = data['actorsMovie']
        boxoffice = data['boxofficeMovie']

        try:
            Movies.objects.get(movie_id=movie_id, user=user)
        except ObjectDoesNotExist:
            Movies.objects.create(movie_id=movie_id, title=title, release=release,
                               runtime=runtime, actors=actors, boxoffice=boxoffice,user=user)
        else:
            return HttpResponse(400) # user should be know what doing wrong :/
        return HttpResponse(201)


class saved_movies(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        user_movies = Movies.objects.filter(user=user)
        movies_list = {
            "user_movies": user_movies
        }
        return render(request, "saved_movies.html", movies_list)

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email = userObj['email']
            password = userObj['password1']
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                User.objects.create_user(username, email, password)
                user = authenticate(username=username, password=password)
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                messages.error(request, "Invalid form!")
                return HttpResponseRedirect(reverse_lazy('omdmain:register'))
    else:
        form = UserRegistrationForm
    return render(request, 'registration/register.html', {'form': form})

django/omdapp/templates/home.html
{%extends "index.html" %}
{% load static %}
{% block inHead %}
<script src="{% static "omdmain/js/script.js" %}"></script>
{% endblock %}
{% block content %}
  <main class="mdl-layout__content mdl-color--grey-100">
	<center>
	<div class="mdl-card mdl-shadow--6dp">
	<div class="mdl-card__title mdl-color--primary mdl-color-text--white">
	<h2 class="mdl-card__title-text">Searching movies app</h2>
    </div>
	</center>
    </div>
    </main>

{% endblock %}

django/omdapp/templates/index.html
{% load static %}

{% block beforeHtml %}
{% endblock %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <script src="{% static "omdmain/js/jquery-3.4.0.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="{% static "omdmain/js/material.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "omdmain/css/material.min.css" %}">
    <link rel="stylesheet" href="{% static "omdmain/css/styles.css" %}">

{% block inHead %}
{% endblock %}

</head>
<body>

<div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
    {% if messages %}
    {% for message in messages %}
        <div class="mdl-js-snackbar mdl-snackbar" id="message">
            <div id="message_text" class="mdl-snackbar__text">{{ message }}</div>
            <button class="mdl-snackbar__action" type="button"></button>
        </div>
    {% endfor %}
    {% endif %}
    {# Material top bar #}
      <header class="mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
        <div class="mdl-layout__header-row">
            <span class="mdl-layout-title">
            {% block header_title %}
            {% endblock %}
            </span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
            <i class="material-icons">more_vert</i>
          </button>
          <nav class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
	        {% if user.is_authenticated %}
            <a class="mdl-menu__item" href="{%url 'logout'%}">Logout</a>
            {% else %}
            <a class="mdl-menu__item" href="{%url 'login'%}">Login</a>
            <a class="mdl-menu__item" href="{%url 'omdmain:register'%}">Register</a>
            {% endif %}
          </nav>
        </div>
        {% block header_tabs %}
        {% endblock %}
      </header>
    {# Material top bar end #}
    {# Material left menu #}
      <div class="demo-drawer mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
          {# Navigation #}
        <nav class="demo-navigation mdl-navigation mdl-color--blue-grey-800">
          <a class="mdl-navigation__link" href="{% url 'omdmain:home' %}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">home</i>Home</a>
            {% if not user.is_authenticated %}
            <!--<a class="mdl-navigation__link" href="{% url 'omdmain:register' %}"><i class="mdl-color-text&#45;&#45;blue-grey-400 material-icons" role="presentation">how_to_reg</i>Register</a>-->
            {% else %}
            <a class="mdl-navigation__link" href="{% url 'omdmain:movies' %}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">format_list_numbered</i>Search Movies</a>
            <a class="mdl-navigation__link" href="{% url 'omdmain:saved_movies' %}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">format_list_numbered</i>Saved Movies</a>
            {% endif %}
          <div class="mdl-layout-spacer"></div>
          <!--<a class="mdl-navigation__link" href="{% url 'omdmain:register' %}"><i class="mdl-color-text&#45;&#45;blue-grey-400 material-icons" role="presentation">help_outline</i><span class="visuallyhidden">About</span></a>-->
        </nav>
          {# Navigation end #}
      </div>
    {# Material left menu end #}
    {% block content %}
    {% endblock %}
</div>
{# Material layout end #}
{% block svgs %}
{% endblock %}
</body>
</html>

django/omdapp/templates/movies.html
{%extends "index.html" %}
{% load static %}
{% block inHead %}
<script src="{% static "omdmain/js/search_movies.js" %}"></script>
{% endblock %}
{% block content %}
  <main class="mdl-layout__content mdl-color--grey-100">
		<center>
	   <div class="mdl-card mdl-shadow--6dp">
                        <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
					<center>
                    <h2 class="mdl-card__title-text">Search movies from IMDB</h2>
					</center>
                </div>
                    <div class="mdl-card__supporting-text">
                        {% csrf_token %}
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" type="text" id="TextBox"
                                   name="TextBox" onkeypress="return enter(event)">
                            <label class="mdl-textfield__label " for="TextBox">Search movie</label>
                        </div>
                        <div class="mdl-card__actions mdl-typography--text-center">
                            <button class="mdl-button mdl-js-button mdl-js-ripple-effect  mdl-button--colored"
                                    onclick="requestAPI()" >Search
                            </button>
                        </div>
                </div>
		<div>
<ul class="mdl-list">
  <li class="mdl-list__item">
    <span id="Title" class="mdl-list__item-primary-content">
    </span>
  </li>
  <li class="mdl-list__item">
    <span id="Release" class="mdl-list__item-primary-content">
    </span>
  </li>
  <li class="mdl-list__item">
    <span id="Runtime" class="mdl-list__item-primary-content">
    </span>
  </li>
	<li class="mdl-list__item">
    <span style="text-align: left" id="Actors" class="mdl-list__item-primary-content">
    </span>
  </li>
	<li class="mdl-list__item">
    <span id="BoxOffice" class="mdl-list__item-primary-content">
    </span>
  </li>
</ul>
		</div>
			<button class="mdl-button mdl-js-button mdl-js-ripple-effect  mdl-button--colored"
			onclick="saveToDb()" id="save_button">Save
			</button>
       </div>
		</center>
    </main>
{% endblock %}

django/omdapp/templates/saved_movies.html
{%extends "index.html" %}
{% load static %}
{% block inHead %}
<script src="{% static "omdmain/js/saved_movies.js" %}"></script>
{% endblock %}
{% block content %}
  <main class="mdl-layout__content mdl-color--grey-100">
		<center>
	   <div class="mdl-card mdl-shadow--6dp">
                        <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
                    <h2 class="mdl-card__title-text">Saved movies</h2>
                </div>
	<ul class="mdl-list">
	{% for movie in user_movies %}
	<li class="mdl-list__item">
	<ul class="mdl-list">
    <li><b>{{ movie.title}}</b></li>
    <li>{{ movie.release}}</li>
    <li>{{ movie.runtime}}</li>
    <li>{{ movie.actors}}</li>
    <li>{{ movie.boxoffice}}</li></ul>
    </li>
	{% endfor %}

	</ul>
       </div>
	<center>
    </main>
{% endblock %}